title:       "orolo.dev"
description: "home of Steve Copley"

address:     "Nelson, NZ"
email:       "admin@orolo.dev"

github:      "https://github.com/stevecopley"
instagram:   "https://www.instagram.com/orolo.dev"
twitter:     "https://twitter.com/OroloDev"

markdown: kramdown

