title:       "orolo.dev"
description: "the home of"
owner:       "Steve Copley"

address:     "Nelson, NZ"
email:       "steve@orolo.dev"

github:      "https://github.com/stevecopley"
linkedin:    "https://www.linkedin.com/in/stevecopley/"
instagram:   "https://www.instagram.com/stevecopley"
twitter:     "https://twitter.com/stevecopley"
# instagram:   "https://www.instagram.com/orolo.dev"
# twitter:     "https://twitter.com/OroloDev"

logo-main:   "analemma-anim-pinkblue.svg"
logo-menu:   "analemma-anim-light.svg"

markdown: kramdown

