title:       "orolo.dev"
description: "the home of"
owner:       "Steve Copley"

address:     "Nelson, NZ"
email:       "steve@orolo.dev"

logo:        "analemma-pinkblue.svg"

markdown:    kramdown

